# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lexical_dfa.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_DFA(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1181, 741)
        self.trans_table = QtWidgets.QTableWidget(Form)
        self.trans_table.setGeometry(QtCore.QRect(20, 30, 1141, 701))
        self.trans_table.setObjectName("trans_table")
        self.trans_table.setColumnCount(21)
        self.trans_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(20, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.trans_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "letter"))
        item = self.trans_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "_"))
        item = self.trans_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "digit"))
        item = self.trans_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "0"))
        item = self.trans_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "1-9"))
        item = self.trans_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "option"))
        item = self.trans_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "/"))
        item = self.trans_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "\""))
        item = self.trans_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "bound"))
        item = self.trans_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "."))
        item = self.trans_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "E"))
        item = self.trans_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "+"))
        item = self.trans_table.horizontalHeaderItem(12)
        item.setText(_translate("Form", "-"))
        item = self.trans_table.horizontalHeaderItem(13)
        item.setText(_translate("Form", "1-7"))
        item = self.trans_table.horizontalHeaderItem(14)
        item.setText(_translate("Form", "x"))
        item = self.trans_table.horizontalHeaderItem(15)
        item.setText(_translate("Form", "0-7"))
        item = self.trans_table.horizontalHeaderItem(16)
        item.setText(_translate("Form", "a-f"))
        item = self.trans_table.horizontalHeaderItem(17)
        item.setText(_translate("Form", "*"))
        item = self.trans_table.horizontalHeaderItem(18)
        item.setText(_translate("Form", "="))
        item = self.trans_table.horizontalHeaderItem(19)
        item.setText(_translate("Form", "other"))
        item = self.trans_table.horizontalHeaderItem(20)
        item.setText(_translate("Form", "legal"))


class Dfa_TransTable(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        self.ui = Ui_DFA()
        self.ui.setupUi(self)
        self.setWindowTitle("TransTable")